# Generated by Django 4.1.7 on 2024-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intensity', models.FloatField()),
                ('Likelihood', models.FloatField()),
                ('Relevance', models.FloatField()),
                ('Year', models.IntegerField()),
                ('Country', models.CharField(max_length=255)),
                ('Topics', models.CharField(max_length=255)),
                ('Region', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
            ],
        ),
    ]
